language: rust

dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdbus-1-3 libdbus-1-dev

rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - |
    [ $TRAVIS_RUST_VERSION != nightly ] ||
    cargo build --verbose --features clippy
