[package]
name = "froyo"
version = "0.1.0"
authors = ["Andy Grover <agrover@redhat.com>"]

[dependencies]
clippy = "0"
devicemapper = "0.3.0"
clap = "1"
nix = "0"
crc = "1"
byteorder = "0.3.13"
uuid = "0.1.18"
time = "0.1"
serde = "*"
serde_json = "*"
serde_macros = "0"
custom_derive = "0.1"
bytesize = "0.1.1"
dbus = "0.3"
term = "0.4"

[dependencies.newtype_derive]
version = "0.1"
default-features = false
features = ["std-unstable"]
