[package]
name = "froyo"
version = "0.1.0"
authors = ["Andy Grover <agrover@redhat.com>"]

[dependencies]
devicemapper = "0.2.0"
clap = "1"
nix = "=0.3.9"
crc = "1"
byteorder = "=0.3.13"
uuid = "=0.1.18"
time = "=0.1.33"
